export const CREATE_SOUS_CAHIER_DE_TEST_REQUEST =
  "CREATE_SOUS_CAHIER_DE_TEST_REQUEST";
export const CREATE_SOUS_CAHIER_DE_TEST_SUCCESS =
  "CREATE_SOUS_CAHIER_DE_TEST_SUCCESS";
export const CREATE_SOUS_CAHIER_DE_TEST_FAILURE =
  "CREATE_SOUS_CAHIER_DE_TEST_FAILURE";

export const GET_SOUS_CAHIER_DE_TESTS_REQUEST =
  "GET_SOUS_CAHIER_DE_TEST_REQUEST";
export const GET_SOUS_CAHIER_DE_TESTS_SUCCESS =
  "GET_SOUS_CAHIER_DE_TEST_SUCCESS";
export const GET_SOUS_CAHIER_DE_TESTS_FAILURE =
  "GET_SOUS_CAHIER_DE_TEST_FAILURE";

export const CLEAR_SOUS_CAHIER = "CLEAR_SOUS_CAHIER";

