export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_ROLE_REQUEST = "GET_ROLE_REQUEST";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";

export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const GET_PROJECT_ROLE_REQUEST = "GET_PROJECT_ROLE_REQUEST";
export const GET_PROJECT_ROLE_SUCCESS = "GET_PROJECT_ROLE_SUCCESS";
export const GET_PROJECT_ROLE_FAILURE = "GET_PROJECT_ROLE_FAILURE";

export const ASSIGN_PROJECT_REQUEST = "ASSIGN_PROJECT_REQUEST";
export const ASSIGN_PROJECT_SUCCESS = "ASSIGN_PROJECT_SUCCESS";
export const ASSIGN_PROJECT_FAILURE = "ASSIGN_PROJECT_FAILURE";

export const ASSIGN_DOMAIN_REQUEST = "ASSIGN_DOMAIN_REQUEST";
export const ASSIGN_DOMAIN_SUCCESS = "ASSIGN_DOMAIN_SUCCESS";
export const ASSIGN_DOMAIN_FAILURE = "ASSIGN_DOMAIN_FAILURE";

export const CREATE_CAHIER_TEST_GLOBAL_REQUEST =
  "CREATE_CAHIER_TEST_GLOBAL_REQUEST";
export const CREATE_CAHIER_TEST_GLOBAL_SUCCESS =
  "CREATE_CAHIER_TEST_GLOBAL_SUCCESS";
export const CREATE_CAHIER_TEST_GLOBAL_FAILURE =
  "CREATE_CAHIER_TEST_GLOBAL_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const SUSPEND_USER_REQUEST = "SUSPEND_USER_REQUEST";
export const SUSPEND_USER_SUCCESS = "SUSPEND_USER_SUCCESS";
export const SUSPEND_USER_FAILURE = "SUSPEND_USER_FAILURE";

export const ACTIVATE_USER_REQUEST = "ACTIVATE_USER_REQUEST";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_FAILURE = "ACTIVATE_USER_FAILURE";

export const GET_DOMAINE_REQUEST = "GET_DOMAINE_REQUEST";
export const GET_DOMAINE_SUCCESS = "GET_DOMAINE_SUCCESS";
export const GET_DOMAINE_FAILURE = "GET_DOMAINE_FAILURE";

export const GET_SOUS_DOMAINE_REQUEST = "GET_SOUS_DOMAINE_REQUEST";
export const GET_SOUS_DOMAINE_SUCCESS = "GET_SOUS_DOMAINE_SUCCESS";
export const GET_SOUS_DOMAINE_FAILURE = "GET_SOUS_DOMAINE_FAILURE";

export const GET_FUNCTIONNALITY_REQUEST = "GET_FUNCTIONNALITY_REQUEST";
export const GET_FUNCTIONNALITY_SUCCESS = "GET_FUNCTIONNALITY_SUCCESS";
export const GET_FUNCTIONNALITY_FAILURE = "GET_FUNCTIONNALITY_FAILURE";

export const CREATE_FUNCTIONNALITY_REQUEST = "CREATE_FUNCTIONNALITY_REQUEST";
export const CREATE_FUNCTIONNALITY_SUCCESS = "CREATE_FUNCTIONNALITY_SUCCESS";
export const CREATE_FUNCTIONNALITY_FAILURE = "CREATE_FUNCTIONNALITY_FAILURE";

export const GET_TEST_CASE_REQUEST = "GET_TEST_CASE_REQUEST";
export const GET_TEST_CASE_SUCCESS = "GET_TEST_CASE_SUCCESS";
export const GET_TEST_CASE_FAILURE = "GET_TEST_CASE_FAILURE";

export const ADD_TEST_CASE_DESCRIPTION_REQUEST =
  "ADD_TEST_CASE_DESCRIPTION_REQUEST";
export const ADD_TEST_CASE_DESCRIPTION_SUCCESS =
  "ADD_TEST_CASE_DESCRIPTION_SUCCESS";
export const ADD_TEST_CASE_DESCRIPTION_FAILURE =
  "ADD_TEST_CASE_DESCRIPTION_FAILURE";

export const GET_STEPS_REQUEST = "GET_STEPS_REQUEST";
export const GET_STEPS_SUCCESS = "GET_STEPS_SUCCESS";
export const GET_STEPS_FAILURE = "GET_STEPS_FAILURE";

export const ASSIGN_TEST_CASE_REQUEST = "ASSIGN_TEST_CASE_REQUEST";
export const ASSIGN_TEST_CASE_SUCCESS = "ASSIGN_TEST_CASE_SUCCESS";
export const ASSIGN_TEST_CASE_FAILURE = "ASSIGN_TEST_CASE_FAILURE";

export const EXECUTE_TEST_CASE_REQUEST = "EXECUTE_TEST_CASE_REQUEST";
export const EXECUTE_TEST_CASE_SUCCESS = "EXECUTE_TEST_CASE_SUCCESS";
export const EXECUTE_TEST_CASE_FAILURE = "EXECUTE_TEST_CASE_FAILURE";

export const CREATE_CAS_TEST_REQUEST = "CREATE_CAS_TEST_REQUEST";
export const CREATE_CAS_TEST_SUCCESS = "CREATE_CAS_TEST_SUCCESS";
export const CREATE_CAS_TEST_FAILURE = "CREATE_CAS_TEST_FAILURE";



export const FETCH_USER_PROJECTS_REQUEST = "FETCH_USER_PROJECTS_REQUEST";
export const FETCH_USER_PROJECTS_SUCCESS = "FETCH_USER_PROJECTS_SUCCESS";
export const FETCH_USER_PROJECTS_FAILURE = "FETCH_USER_PROJECTS_FAILURE";

export const SUBMIT_TEST_RESULT_REQUEST = "SUBMIT_TEST_RESULT_REQUEST";
export const SUBMIT_TEST_RESULT_SUCCESS = "SUBMIT_TEST_RESULT_SUCCESS";
export const SUBMIT_TEST_RESULT_FAILURE = "SUBMIT_TEST_RESULT_FAILURE";

export const GET_TEST_RESULT_REQUEST = "GET_TEST_RESULT_REQUEST";
export const GET_TEST_RESULT_SUCCESS = "GET_TEST_RESULT_SUCCESS";
export const GET_TEST_RESULT_FAILURE = "GET_TEST_RESULT_FAILURE";


export const CREATE_SOUS_DOMAINE_REQUEST = "CREATE_SOUS_DOMAINE_REQUEST";
export const CREATE_SOUS_DOMAINE_SUCCESS = "CREATE_SOUS_DOMAINE_SUCCESS";
export const CREATE_SOUS_DOMAINE_FAILURE = "CREATE_SOUS_DOMAINE_FAILURE";

export const CREATE_DOMAINE_REQUEST = "CREATE_DOMAINE_REQUEST";
export const CREATE_DOMAINE_SUCCESS = "CREATE_DOMAINE_SUCCESS";
export const CREATE_DOMAINE_FAILURE = "CREATE_DOMAINE_FAILURE";



export const LOGOUT = "LOGOUT";
