export const GET_TOTAL_USERS_REQUEST = "GET_TOTAL_USERS_REQUEST";
export const GET_TOTAL_USERS_SUCCESS = "GET_TOTAL_USERS_SUCCESS";
export const GET_TOTAL_USERS_FAILURE = "GET_TOTAL_USERS_FAILURE";

export const GET_TOTAL_PROJECTS_REQUEST = "GET_TOTAL_PROJECTS_REQUEST";
export const GET_TOTAL_PROJECTS_SUCCESS = "GET_TOTAL_PROJECTS_SUCCESS";
export const GET_TOTAL_PROJECTS_FAILURE = "GET_TOTAL_PROJECTS_FAILURE";

export const FETCH_COMPLETED_PROJECTS_COUNT_REQUEST =
  "FETCH_COMPLETED_PROJECTS_COUNT_REQUEST";
export const FETCH_COMPLETED_PROJECTS_COUNT_SUCCESS =
  "FETCH_COMPLETED_PROJECTS_COUNT_SUCCESS";
export const FETCH_COMPLETED_PROJECTS_COUNT_FAILURE =
  "FETCH_COMPLETED_PROJECTS_COUNT_FAILURE";

export const FETCH_IN_PROGRESS_PROJECTS_COUNT_REQUEST =
  "FETCH_IN_PROGRESS_PROJECTS_COUNT_REQUEST";
export const FETCH_IN_PROGRESS_PROJECTS_COUNT_SUCCESS =
  "FETCH_IN_PROGRESS_PROJECTS_COUNT_SUCCESS";
export const FETCH_IN_PROGRESS_PROJECTS_COUNT_FAILURE =
  "FETCH_IN_PROGRESS_PROJECTS_COUNT_FAILURE";

  export const GET_PROJECT_COUNTS_REQUEST = "GET_PROJECT_COUNTS_REQUEST";
  export const GET_PROJECT_COUNTS_SUCCESS = "GET_PROJECT_COUNTS_SUCCESS";
  export const GET_PROJECT_COUNTS_FAILURE = "GET_PROJECT_COUNTS_FAILURE";

  //last login

  // actionTypes.js
export const GET_LAST_LOGINS_REQUEST = "GET_LAST_LOGINS_REQUEST";
export const GET_LAST_LOGINS_SUCCESS = "GET_LAST_LOGINS_SUCCESS";
export const GET_LAST_LOGINS_FAILURE = "GET_LAST_LOGINS_FAILURE";

export const GET_PROJECT_TEST_CASE_COUNTS_REQUEST = "GET_PROJECT_TEST_CASE_COUNTS_REQUEST";
export const GET_PROJECT_TEST_CASE_COUNTS_SUCCESS = "GET_PROJECT_TEST_CASE_COUNTS_SUCCESS";
export const GET_PROJECT_TEST_CASE_COUNTS_FAILURE = "GET_PROJECT_TEST_CASE_COUNTS_FAILURE";

